/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhahang.ui;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.String;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import keeptoo.Drag;
import keeptoo.KButton;
import java.util.Date;
import quanlynhahang.helper.Auth;
import quanlynhahang.helper.MsgBox;
import javax.swing.Timer;
import quanlynhahang.helper.XDate;
/**
 *
 * @author Tuan Anh
 */
public class Main extends javax.swing.JFrame {


    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
        new LoginJDialog(this,true).setVisible(true);
        new TimeJDialog(this,true).setVisible(true);
        this.innit();
    }
    
    public Main(int so){
        initComponents();
        new TimeJDialog(this,true).setVisible(true);
        this.innit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new keeptoo.KGradientPanel();
        pnladd = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lblExit = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblVaitro = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnHoadon = new keeptoo.KButton();
        btnMenu = new keeptoo.KButton();
        btnOrder = new keeptoo.KButton();
        btnBan = new keeptoo.KButton();
        btnThongKe = new keeptoo.KButton();
        btnTrangchu = new keeptoo.KButton();
        lblTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAboutUs = new javax.swing.JLabel();
        btnNhanVien = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pnlMain.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlMain.setkEndColor(new java.awt.Color(98, 40, 117));
        pnlMain.setkGradientFocus(50);
        pnlMain.setkStartColor(new java.awt.Color(160, 40, 163));
        pnlMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlMainMouseDragged(evt);
            }
        });
        pnlMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlMainMousePressed(evt);
            }
        });
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnladd.setBackground(new java.awt.Color(255, 255, 255));
        pnladd.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(196, 163, 90)));
        pnladd.setForeground(new java.awt.Color(255, 255, 255));
        pnladd.setRequestFocusEnabled(false);
        pnladd.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout pnladdLayout = new javax.swing.GroupLayout(pnladd);
        pnladd.setLayout(pnladdLayout);
        pnladdLayout.setHorizontalGroup(
            pnladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        pnladdLayout.setVerticalGroup(
            pnladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        pnlMain.add(pnladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 1230, 630));

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/icon/iconfinder_icons_exit2_1564506.png"))); // NOI18N
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        pnlMain.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 30, -1));
        pnlMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/icon/iconfinder_Change_password_7023958 (1).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        pnlMain.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 40, 30));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(105, 43, 125));
        kGradientPanel2.setkGradientFocus(800);
        kGradientPanel2.setkStartColor(new java.awt.Color(160, 40, 163));

        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/icon/iconfinder_Artboard_1_1790660.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGap(0, 1478, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlMain.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 30));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/icon/logoHimari1.png"))); // NOI18N
        jLabel18.setToolTipText("");
        pnlMain.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 172, 178));

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTen.setForeground(new java.awt.Color(255, 255, 255));
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Người Dùng : AAA");
        pnlMain.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 230, -1));

        lblVaitro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVaitro.setForeground(new java.awt.Color(255, 255, 255));
        lblVaitro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVaitro.setText("Chức Vụ : Nhân Viên");
        pnlMain.add(lblVaitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 190, -1));

        lblDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/icon/calendar.png"))); // NOI18N
        lblDate.setText("20 - 11 - 2020");
        pnlMain.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 140, -1));

        btnHoadon.setText("HÓA ĐƠN");
        btnHoadon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHoadon.setkBorderRadius(30);
        btnHoadon.setkEndColor(new java.awt.Color(234, 250, 124));
        btnHoadon.setkForeGround(new java.awt.Color(61, 21, 94));
        btnHoadon.setkHoverColor(new java.awt.Color(255, 51, 102));
        btnHoadon.setkHoverEndColor(new java.awt.Color(251, 168, 126));
        btnHoadon.setkHoverForeGround(new java.awt.Color(61, 21, 94));
        btnHoadon.setkHoverStartColor(new java.awt.Color(234, 250, 124));
        btnHoadon.setkStartColor(new java.awt.Color(239, 97, 254));
        btnHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHoadonMousePressed(evt);
            }
        });
        pnlMain.add(btnHoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 680, 160, 90));

        btnMenu.setText("MENU");
        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMenu.setkBorderRadius(30);
        btnMenu.setkEndColor(new java.awt.Color(234, 250, 124));
        btnMenu.setkForeGround(new java.awt.Color(61, 21, 94));
        btnMenu.setkHoverColor(new java.awt.Color(255, 51, 102));
        btnMenu.setkHoverEndColor(new java.awt.Color(251, 168, 126));
        btnMenu.setkHoverForeGround(new java.awt.Color(61, 21, 94));
        btnMenu.setkHoverStartColor(new java.awt.Color(234, 250, 124));
        btnMenu.setkStartColor(new java.awt.Color(239, 97, 254));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
        });
        pnlMain.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 680, 160, 90));

        btnOrder.setText("ORDER");
        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOrder.setkBorderRadius(30);
        btnOrder.setkEndColor(new java.awt.Color(234, 250, 124));
        btnOrder.setkForeGround(new java.awt.Color(61, 21, 94));
        btnOrder.setkHoverColor(new java.awt.Color(255, 51, 102));
        btnOrder.setkHoverEndColor(new java.awt.Color(251, 168, 126));
        btnOrder.setkHoverForeGround(new java.awt.Color(61, 21, 94));
        btnOrder.setkHoverStartColor(new java.awt.Color(234, 250, 124));
        btnOrder.setkStartColor(new java.awt.Color(239, 97, 254));
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOrderMousePressed(evt);
            }
        });
        pnlMain.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 680, 160, 90));

        btnBan.setText("BÀN");
        btnBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBan.setkBorderRadius(30);
        btnBan.setkEndColor(new java.awt.Color(234, 250, 124));
        btnBan.setkForeGround(new java.awt.Color(61, 21, 94));
        btnBan.setkHoverColor(new java.awt.Color(255, 51, 102));
        btnBan.setkHoverEndColor(new java.awt.Color(251, 168, 126));
        btnBan.setkHoverForeGround(new java.awt.Color(61, 21, 94));
        btnBan.setkHoverStartColor(new java.awt.Color(234, 250, 124));
        btnBan.setkStartColor(new java.awt.Color(239, 97, 254));
        btnBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBanMousePressed(evt);
            }
        });
        pnlMain.add(btnBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 680, 160, 90));

        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThongKe.setkBorderRadius(30);
        btnThongKe.setkEndColor(new java.awt.Color(234, 250, 124));
        btnThongKe.setkForeGround(new java.awt.Color(61, 21, 94));
        btnThongKe.setkHoverColor(new java.awt.Color(255, 51, 102));
        btnThongKe.setkHoverEndColor(new java.awt.Color(251, 168, 126));
        btnThongKe.setkHoverForeGround(new java.awt.Color(61, 21, 94));
        btnThongKe.setkHoverStartColor(new java.awt.Color(234, 250, 124));
        btnThongKe.setkStartColor(new java.awt.Color(239, 97, 254));
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThongKeMousePressed(evt);
            }
        });
        pnlMain.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 680, 160, 90));

        btnTrangchu.setText("TRANG CHỦ");
        btnTrangchu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTrangchu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTrangchu.setkBackGroundColor(new java.awt.Color(234, 250, 124));
        btnTrangchu.setkBorderRadius(30);
        btnTrangchu.setkEndColor(new java.awt.Color(234, 250, 124));
        btnTrangchu.setkForeGround(new java.awt.Color(61, 21, 94));
        btnTrangchu.setkHoverColor(new java.awt.Color(234, 250, 124));
        btnTrangchu.setkHoverEndColor(new java.awt.Color(251, 168, 126));
        btnTrangchu.setkHoverForeGround(new java.awt.Color(61, 21, 94));
        btnTrangchu.setkHoverStartColor(new java.awt.Color(234, 250, 124));
        btnTrangchu.setkIndicatorColor(new java.awt.Color(234, 250, 124));
        btnTrangchu.setkPressedColor(new java.awt.Color(234, 250, 124));
        btnTrangchu.setkSelectedColor(new java.awt.Color(234, 250, 124));
        btnTrangchu.setkStartColor(new java.awt.Color(239, 97, 254));
        btnTrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrangchuMousePressed(evt);
            }
        });
        pnlMain.add(btnTrangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 160, 90));

        lblTime.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/icon/clock.png"))); // NOI18N
        lblTime.setText("10:20:00 AM");
        pnlMain.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 140, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("XIN CHÀO");
        pnlMain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 220, -1));

        lblAboutUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/icon/iconfinder_world_www_web_website_5340283.png"))); // NOI18N
        lblAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutUsMouseClicked(evt);
            }
        });
        pnlMain.add(lblAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNhanVien.setkBorderRadius(30);
        btnNhanVien.setkEndColor(new java.awt.Color(234, 250, 124));
        btnNhanVien.setkForeGround(new java.awt.Color(61, 21, 94));
        btnNhanVien.setkHoverColor(new java.awt.Color(255, 51, 102));
        btnNhanVien.setkHoverEndColor(new java.awt.Color(251, 168, 126));
        btnNhanVien.setkHoverForeGround(new java.awt.Color(61, 21, 94));
        btnNhanVien.setkHoverStartColor(new java.awt.Color(234, 250, 124));
        btnNhanVien.setkStartColor(new java.awt.Color(239, 97, 254));
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNhanVienMousePressed(evt);
            }
        });
        pnlMain.add(btnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 680, 160, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlMainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMainMouseDragged
        // TODO add your handling code here:
        new Drag(pnlMain).moveWindow(evt);
    }//GEN-LAST:event_pnlMainMouseDragged

    private void pnlMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMainMousePressed
         // TODO add your handling code here:
         new Drag(pnlMain).onPress(evt);
    }//GEN-LAST:event_pnlMainMousePressed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        if(MsgBox.confirm(this, "Bạn muốn tắt chương trình ?")){
            System.exit(0);
        }
    }//GEN-LAST:event_lblExitMouseClicked

    //btnMenu 
    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        // TODO add your handling code here:
        this.setColor(btnMenu);
        this.resetColor(btnBan);
        this.resetColor(btnOrder);
        this.resetColor(btnHoadon);
        this.resetColor(btnTrangchu);
        this.resetColor(btnNhanVien);
        this.resetColor(btnThongKe);
        this.addPanel(new MeNuJPanel());
        this.addPanel(new MeNuJPanel());
    }//GEN-LAST:event_btnMenuMousePressed

    //btnBan
    private void btnBanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanMousePressed
        // TODO add your handling code here:
        this.setColor(btnBan);
        this.resetColor(btnMenu);
        this.resetColor(btnOrder);
        this.resetColor(btnHoadon);
        this.resetColor(btnTrangchu);
        this.resetColor(btnNhanVien);
        this.resetColor(btnThongKe);
        this.addPanel(new BanJPanel());
    }//GEN-LAST:event_btnBanMousePressed

    //btnOrder
    private void btnOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMousePressed
        // TODO add your handling code here:
        this.setColor(btnOrder);
        this.resetColor(btnMenu);
        this.resetColor(btnBan);
        this.resetColor(btnHoadon);
        this.resetColor(btnTrangchu);
        this.resetColor(btnNhanVien);
        this.resetColor(btnThongKe);
        this.addPanel(new OrderJPanel());
    }//GEN-LAST:event_btnOrderMousePressed

    //btnHoaDon
    private void btnHoadonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoadonMousePressed
        // TODO add your handling code here:
        this.setColor(btnHoadon);
        this.resetColor(btnBan);
        this.resetColor(btnOrder);
        this.resetColor(btnMenu);
        this.resetColor(btnTrangchu);
        this.resetColor(btnNhanVien);
        this.resetColor(btnThongKe);
        this.addPanel(new HoaDonJPanel());
    }//GEN-LAST:event_btnHoadonMousePressed

    //btnTrangChu
    private void btnTrangchuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangchuMousePressed
        // TODO add your handling code here:
        this.setColor(btnTrangchu);
        this.resetColor(btnBan);
        this.resetColor(btnOrder);
        this.resetColor(btnHoadon);
        this.resetColor(btnMenu);
        this.resetColor(btnNhanVien);
        this.resetColor(btnThongKe);
        this.addPanel(new TrangChuJPanel());
    }//GEN-LAST:event_btnTrangchuMousePressed

    //btnNhanVien
    private void btnNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMousePressed
        // TODO add your handling code here:
        if(!Auth.isManager()){
            MsgBox.alert(this, "Bạn không được cấp quyền truy cập");
            return;
        }
        else{
            this.setColor(btnNhanVien);
            this.resetColor(btnBan);
            this.resetColor(btnOrder);
            this.resetColor(btnHoadon);
            this.resetColor(btnTrangchu);
            this.resetColor(btnMenu);
            this.resetColor(btnThongKe);
            this.addPanel(new NhanVienJPanel());
        }
    }//GEN-LAST:event_btnNhanVienMousePressed

    //btnThongke
    private void btnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMousePressed
        // TODO add your handling code here:
        if(!Auth.isManager()){
            MsgBox.alert(this, "Bạn không được cấp quyền truy cập");
            return;
        }
        else{
            this.setColor(btnThongKe);
            this.resetColor(btnBan);
            this.resetColor(btnOrder);
            this.resetColor(btnHoadon);
            this.resetColor(btnTrangchu);
            this.resetColor(btnNhanVien);
            this.resetColor(btnMenu);
            this.addPanel(new ThongKeJPanel());
        }
        
    }//GEN-LAST:event_btnThongKeMousePressed

    //lbl Logout
    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        if(MsgBox.confirm(this, "Bạn muốn đăng xuất tài khoản ?")){   
            this.dispose();
            new Main().setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    //lbl Đổi mk
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new DoiMkJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    //lbl about us
    private void lblAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutUsMouseClicked
        // TODO add your handling code here:
        new AboutUsJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_lblAboutUsMouseClicked

    
    //innit
    public void innit(){
        this.setLocationRelativeTo(null);
        this.addPanel(new TrangChuJPanel());
        this.setColor(btnTrangchu);
        this.setTime();
        lblTen.setText(Auth.user.getTenNV());
        lblVaitro.setText(Auth.user.getVaiTro()?"Vai Trò : Quản Lý":"Vai Trò : Nhân Viên");
        this.updateStatus();
    }
    
    //add Panel
    public static void addPanel(JPanel panel){
        pnladd.removeAll();
        pnladd.setLayout(new BorderLayout());
        pnladd.add(panel, BorderLayout.CENTER);
        pnladd.validate();
    }
    
    //set color
    public void setColor(KButton btn){
        btn.setkStartColor(new Color(234,250,124));
        btn.setkEndColor(new Color(251,168,126));
    }
    
    //reset color
    public void resetColor(KButton btn){
        btn.setkStartColor(new Color(239,97,254));
        btn.setkEndColor(new Color(234,250,124));
    }
    
    //set hiển thị thời gian
    public void setTime(){
        new Timer(1000, new ActionListener() {
            SimpleDateFormat fm = new SimpleDateFormat("hh:mm:ss a");
            public void actionPerformed(ActionEvent e) {
                lblTime.setText(fm.format(new Date()));
            }
        }).start();
        
        lblDate.setText(XDate.toString(new Date(), "dd - MM - yyyy"));
    }
    
    
    //update status theo chức vụ
    public void updateStatus(){
        if(!Auth.isManager()){
            setBtn(btnNhanVien);
            setBtn(btnThongKe);
        }
        else{
            resetBtn(btnNhanVien);
            resetBtn(btnThongKe);
        }
    }
    
    //khóa btn với vai trò nhân viên
    public static void setBtn(KButton btn){
        btn.setEnabled(false);
        btn.setkStartColor(new Color(204,204,204));
        btn.setkEndColor(new Color(204,204,204));
    }
    
    //reset status cho btn
    public static void resetBtn(KButton btn){
        btn.setEnabled(true);
        btn.setkStartColor(new Color(239,97,254));
        btn.setkEndColor(new Color(234,250,124));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void addpanel(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static keeptoo.KButton btnBan;
    private keeptoo.KButton btnHoadon;
    private keeptoo.KButton btnMenu;
    private keeptoo.KButton btnNhanVien;
    public static keeptoo.KButton btnOrder;
    private keeptoo.KButton btnThongKe;
    private keeptoo.KButton btnTrangchu;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblVaitro;
    public static keeptoo.KGradientPanel pnlMain;
    public static javax.swing.JPanel pnladd;
    // End of variables declaration//GEN-END:variables
}
