/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhahang.ui;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import keeptoo.KButton;
import quanlynhahang.dao.SanPhamDAO;
import quanlynhahang.entity.SanPham;
import quanlynhahang.helper.Auth;
import quanlynhahang.helper.MsgBox;
import quanlynhahang.helper.XImage;
import quanlynhahang.helper.XMoney;
import quanlynhahang.panelChild.MenuPanelChild;
/**
 *
 * @author SONY
 */
public class MeNuJPanel extends javax.swing.JPanel {

    SanPham sp;
    
    /**
     * Creates new form MenuJPanel
     */
    public MeNuJPanel() {
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        pnl1 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        pnlKhaivi = new javax.swing.JPanel();
        jPanel161 = new javax.swing.JPanel();
        jLabel486 = new javax.swing.JLabel();
        jLabel487 = new javax.swing.JLabel();
        jLabel488 = new javax.swing.JLabel();
        jPanel176 = new javax.swing.JPanel();
        jLabel531 = new javax.swing.JLabel();
        jLabel532 = new javax.swing.JLabel();
        jLabel533 = new javax.swing.JLabel();
        jPanel172 = new javax.swing.JPanel();
        jLabel519 = new javax.swing.JLabel();
        jLabel520 = new javax.swing.JLabel();
        jLabel521 = new javax.swing.JLabel();
        jPanel171 = new javax.swing.JPanel();
        jLabel516 = new javax.swing.JLabel();
        jLabel517 = new javax.swing.JLabel();
        jLabel518 = new javax.swing.JLabel();
        jPanel162 = new javax.swing.JPanel();
        jLabel489 = new javax.swing.JLabel();
        jLabel490 = new javax.swing.JLabel();
        jLabel491 = new javax.swing.JLabel();
        jPanel175 = new javax.swing.JPanel();
        jLabel528 = new javax.swing.JLabel();
        jLabel529 = new javax.swing.JLabel();
        jLabel530 = new javax.swing.JLabel();
        jPanel173 = new javax.swing.JPanel();
        jLabel522 = new javax.swing.JLabel();
        jLabel523 = new javax.swing.JLabel();
        jLabel524 = new javax.swing.JLabel();
        jPanel174 = new javax.swing.JPanel();
        jLabel525 = new javax.swing.JLabel();
        jLabel526 = new javax.swing.JLabel();
        jLabel527 = new javax.swing.JLabel();
        jPanel170 = new javax.swing.JPanel();
        jLabel513 = new javax.swing.JLabel();
        jLabel514 = new javax.swing.JLabel();
        jLabel515 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        jScrollPane25 = new javax.swing.JScrollPane();
        pnlSushi = new javax.swing.JPanel();
        pnl3 = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        pnlDiemtam = new javax.swing.JPanel();
        pnl4 = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        pnlTempura = new javax.swing.JPanel();
        pnl5 = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        pnlTrangMieng = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlChitiet = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jLabel161 = new javax.swing.JLabel();
        txtTenmon = new javax.swing.JTextField();
        jLabel162 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        rdoCon = new javax.swing.JRadioButton();
        rdoHet = new javax.swing.JRadioButton();
        jLabel166 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        cboLoai = new javax.swing.JComboBox<>();
        jPanel52 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        btnMoi = new keeptoo.KButton();
        btnThem = new keeptoo.KButton();
        btnSua = new keeptoo.KButton();
        btnXoa = new keeptoo.KButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 230, 254));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabbedPane4.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane4.setForeground(new java.awt.Color(51, 102, 0));
        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setForeground(new java.awt.Color(153, 0, 0));
        pnl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jScrollPane21.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane21.setBorder(null);
        jScrollPane21.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane21.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlKhaivi.setBackground(new java.awt.Color(255, 255, 255));
        pnlKhaivi.setLayout(new java.awt.GridLayout(0, 3, 10, 12));

        jPanel161.setBackground(new java.awt.Color(255, 255, 255));
        jPanel161.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel161.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel486.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel486.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel486.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel486.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel487.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel487.setForeground(new java.awt.Color(153, 51, 0));
        jLabel487.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel487.setText("Trứng hấp");

        jLabel488.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel488.setForeground(new java.awt.Color(51, 0, 51));
        jLabel488.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel488.setText("VND 68,000");

        javax.swing.GroupLayout jPanel161Layout = new javax.swing.GroupLayout(jPanel161);
        jPanel161.setLayout(jPanel161Layout);
        jPanel161Layout.setHorizontalGroup(
            jPanel161Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel487, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel488, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel161Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel486, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel161Layout.setVerticalGroup(
            jPanel161Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel161Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel486, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel487)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel488)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel161);

        jPanel176.setBackground(new java.awt.Color(255, 255, 255));
        jPanel176.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel176.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel531.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel531.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel531.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel531.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel532.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel532.setForeground(new java.awt.Color(153, 51, 0));
        jLabel532.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel532.setText("Trứng hấp");

        jLabel533.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel533.setForeground(new java.awt.Color(51, 0, 51));
        jLabel533.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel533.setText("VND 68,000");

        javax.swing.GroupLayout jPanel176Layout = new javax.swing.GroupLayout(jPanel176);
        jPanel176.setLayout(jPanel176Layout);
        jPanel176Layout.setHorizontalGroup(
            jPanel176Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel532, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel533, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel176Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel531, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel176Layout.setVerticalGroup(
            jPanel176Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel176Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel531, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel532)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel533)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel176);

        jPanel172.setBackground(new java.awt.Color(255, 255, 255));
        jPanel172.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel172.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel519.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel519.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel519.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel519.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel520.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel520.setForeground(new java.awt.Color(153, 51, 0));
        jLabel520.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel520.setText("Trứng hấp");

        jLabel521.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel521.setForeground(new java.awt.Color(51, 0, 51));
        jLabel521.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel521.setText("VND 68,000");

        javax.swing.GroupLayout jPanel172Layout = new javax.swing.GroupLayout(jPanel172);
        jPanel172.setLayout(jPanel172Layout);
        jPanel172Layout.setHorizontalGroup(
            jPanel172Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel520, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel521, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel172Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel519, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel172Layout.setVerticalGroup(
            jPanel172Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel172Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel519, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel520)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel521)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel172);

        jPanel171.setBackground(new java.awt.Color(255, 255, 255));
        jPanel171.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel171.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel516.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel516.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel516.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel516.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel517.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel517.setForeground(new java.awt.Color(153, 51, 0));
        jLabel517.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel517.setText("Trứng hấp");

        jLabel518.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel518.setForeground(new java.awt.Color(51, 0, 51));
        jLabel518.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel518.setText("VND 68,000");

        javax.swing.GroupLayout jPanel171Layout = new javax.swing.GroupLayout(jPanel171);
        jPanel171.setLayout(jPanel171Layout);
        jPanel171Layout.setHorizontalGroup(
            jPanel171Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel517, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel518, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel171Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel516, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel171Layout.setVerticalGroup(
            jPanel171Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel171Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel516, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel517)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel518)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel171);

        jPanel162.setBackground(new java.awt.Color(255, 255, 255));
        jPanel162.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel162.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel489.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel489.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel489.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel489.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel490.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel490.setForeground(new java.awt.Color(153, 51, 0));
        jLabel490.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel490.setText("Trứng hấp");

        jLabel491.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel491.setForeground(new java.awt.Color(51, 0, 51));
        jLabel491.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel491.setText("VND 68,000");

        javax.swing.GroupLayout jPanel162Layout = new javax.swing.GroupLayout(jPanel162);
        jPanel162.setLayout(jPanel162Layout);
        jPanel162Layout.setHorizontalGroup(
            jPanel162Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel490, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel491, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel162Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel489, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel162Layout.setVerticalGroup(
            jPanel162Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel162Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel489, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel490)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel491)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel162);

        jPanel175.setBackground(new java.awt.Color(255, 255, 255));
        jPanel175.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel175.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel528.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel528.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel528.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel528.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel529.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel529.setForeground(new java.awt.Color(153, 51, 0));
        jLabel529.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel529.setText("Trứng hấp");

        jLabel530.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel530.setForeground(new java.awt.Color(51, 0, 51));
        jLabel530.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel530.setText("VND 68,000");

        javax.swing.GroupLayout jPanel175Layout = new javax.swing.GroupLayout(jPanel175);
        jPanel175.setLayout(jPanel175Layout);
        jPanel175Layout.setHorizontalGroup(
            jPanel175Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel529, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel530, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel175Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel528, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel175Layout.setVerticalGroup(
            jPanel175Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel175Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel528, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel529)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel530)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel175);

        jPanel173.setBackground(new java.awt.Color(255, 255, 255));
        jPanel173.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel173.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel522.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel522.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel522.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel522.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel523.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel523.setForeground(new java.awt.Color(153, 51, 0));
        jLabel523.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel523.setText("Trứng hấp");

        jLabel524.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel524.setForeground(new java.awt.Color(51, 0, 51));
        jLabel524.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel524.setText("VND 68,000");

        javax.swing.GroupLayout jPanel173Layout = new javax.swing.GroupLayout(jPanel173);
        jPanel173.setLayout(jPanel173Layout);
        jPanel173Layout.setHorizontalGroup(
            jPanel173Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel523, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel524, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel173Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel522, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel173Layout.setVerticalGroup(
            jPanel173Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel173Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel522, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel523)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel524)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel173);

        jPanel174.setBackground(new java.awt.Color(255, 255, 255));
        jPanel174.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel174.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel525.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel525.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel525.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel525.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel526.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel526.setForeground(new java.awt.Color(153, 51, 0));
        jLabel526.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel526.setText("Trứng hấp");

        jLabel527.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel527.setForeground(new java.awt.Color(51, 0, 51));
        jLabel527.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel527.setText("VND 68,000");

        javax.swing.GroupLayout jPanel174Layout = new javax.swing.GroupLayout(jPanel174);
        jPanel174.setLayout(jPanel174Layout);
        jPanel174Layout.setHorizontalGroup(
            jPanel174Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel526, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel527, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel174Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel525, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel174Layout.setVerticalGroup(
            jPanel174Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel174Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel525, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel526)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel527)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel174);

        jPanel170.setBackground(new java.awt.Color(255, 255, 255));
        jPanel170.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel170.setPreferredSize(new java.awt.Dimension(200, 177));

        jLabel513.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel513.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhahang/image/sushi.jpg"))); // NOI18N
        jLabel513.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel513.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel514.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel514.setForeground(new java.awt.Color(153, 51, 0));
        jLabel514.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel514.setText("Trứng hấp");

        jLabel515.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel515.setForeground(new java.awt.Color(51, 0, 51));
        jLabel515.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel515.setText("VND 68,000");

        javax.swing.GroupLayout jPanel170Layout = new javax.swing.GroupLayout(jPanel170);
        jPanel170.setLayout(jPanel170Layout);
        jPanel170Layout.setHorizontalGroup(
            jPanel170Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel514, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel515, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel170Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel513, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel170Layout.setVerticalGroup(
            jPanel170Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel170Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel513, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel514)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel515)
                .addContainerGap())
        );

        pnlKhaivi.add(jPanel170);

        jScrollPane21.setViewportView(pnlKhaivi);

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane4.addTab("Khai Vị", pnl1);

        pnl2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane25.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane25.setBorder(null);
        jScrollPane25.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane25.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlSushi.setBackground(new java.awt.Color(255, 255, 255));
        pnlSushi.setLayout(new java.awt.GridLayout(0, 3, 10, 12));
        jScrollPane25.setViewportView(pnlSushi);

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane4.addTab("Sashimi - Sushi", pnl2);

        pnl3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane24.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane24.setBorder(null);
        jScrollPane24.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane24.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlDiemtam.setBackground(new java.awt.Color(255, 255, 255));
        pnlDiemtam.setLayout(new java.awt.GridLayout(0, 3, 10, 12));
        jScrollPane24.setViewportView(pnlDiemtam);

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane4.addTab("Điểm Tâm", pnl3);

        pnl4.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane23.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane23.setBorder(null);
        jScrollPane23.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane23.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlTempura.setBackground(new java.awt.Color(255, 255, 255));
        pnlTempura.setLayout(new java.awt.GridLayout(0, 3, 10, 12));
        jScrollPane23.setViewportView(pnlTempura);

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane4.addTab("Tempura & Yaki", pnl4);

        pnl5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane22.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane22.setBorder(null);
        jScrollPane22.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane22.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlTrangMieng.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrangMieng.setLayout(new java.awt.GridLayout(0, 3, 10, 12));
        jScrollPane22.setViewportView(pnlTrangMieng);

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane4.addTab("Tráng Miệng", pnl5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("THỰC ĐƠN");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane4)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlChitiet.setBackground(new java.awt.Color(255, 255, 255));
        pnlChitiet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel51.setBackground(new java.awt.Color(255, 255, 255));
        jPanel51.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông Tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 0, 0))), "Thông Tin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 0, 0))); // NOI18N

        jLabel161.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel161.setText("Tên Món :");

        txtTenmon.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel162.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel162.setText("Giá :");

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel163.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel163.setText("Loại :");

        jLabel164.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel164.setText("Trạng Thái :");

        buttonGroup1.add(rdoCon);
        rdoCon.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rdoCon.setSelected(true);
        rdoCon.setText("Còn Hàng");

        buttonGroup1.add(rdoHet);
        rdoHet.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rdoHet.setText("Hết Hàng");

        jLabel166.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel166.setText("Mô Tả :");

        txtMota.setColumns(20);
        txtMota.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtMota.setRows(5);
        jScrollPane1.setViewportView(txtMota);

        cboLoai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khai Vị", "Sashimi & Sushi", "Điểm Tâm", "Tepura & Yaki", "Tráng Miệng" }));

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel51Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel166)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel51Layout.createSequentialGroup()
                                .addComponent(rdoCon)
                                .addGap(18, 18, 18)
                                .addComponent(rdoHet)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel51Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel51Layout.createSequentialGroup()
                                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel162, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel163, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel164, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel51Layout.createSequentialGroup()
                                .addComponent(jLabel161)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel161)
                    .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel162)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel163)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel164)
                    .addComponent(rdoCon)
                    .addComponent(rdoHet))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel166)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel52.setBackground(new java.awt.Color(255, 255, 255));
        jPanel52.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hình", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 0, 0))); // NOI18N

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnMoi.setText("Mới");
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMoi.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnMoi.setkBorderRadius(15);
        btnMoi.setkEndColor(new java.awt.Color(255, 204, 204));
        btnMoi.setkForeGround(new java.awt.Color(0, 0, 0));
        btnMoi.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        btnMoi.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnMoi.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        btnMoi.setkStartColor(new java.awt.Color(153, 255, 153));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnThem.setkBorderRadius(15);
        btnThem.setkEndColor(new java.awt.Color(255, 204, 204));
        btnThem.setkForeGround(new java.awt.Color(0, 0, 0));
        btnThem.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        btnThem.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnThem.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        btnThem.setkStartColor(new java.awt.Color(153, 255, 153));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnSua.setkBorderRadius(15);
        btnSua.setkEndColor(new java.awt.Color(255, 204, 204));
        btnSua.setkForeGround(new java.awt.Color(0, 0, 0));
        btnSua.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        btnSua.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnSua.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        btnSua.setkStartColor(new java.awt.Color(153, 255, 153));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnXoa.setkBorderRadius(15);
        btnXoa.setkEndColor(new java.awt.Color(255, 204, 204));
        btnXoa.setkForeGround(new java.awt.Color(0, 0, 0));
        btnXoa.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        btnXoa.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnXoa.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        btnXoa.setkStartColor(new java.awt.Color(153, 255, 153));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("THÔNG TIN MÓN ĂN");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlChitietLayout = new javax.swing.GroupLayout(pnlChitiet);
        pnlChitiet.setLayout(pnlChitietLayout);
        pnlChitietLayout.setHorizontalGroup(
            pnlChitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChitietLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlChitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChitietLayout.createSequentialGroup()
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel51, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChitietLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChitietLayout.setVerticalGroup(
            pnlChitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChitietLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlChitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(pnlChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChitiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    //btn xoa
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.deleteSP();
    }//GEN-LAST:event_btnXoaActionPerformed

    //btn Mới
    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    //btn Thêm
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.addSP();
    }//GEN-LAST:event_btnThemActionPerformed

    //btn sửa
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.editSP();
    }//GEN-LAST:event_btnSuaActionPerformed

    //lbl Hình
    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:
        this.getImg();
    }//GEN-LAST:event_lblHinhMouseClicked

    SanPhamDAO spd = new SanPhamDAO();
    
    public void init(){
        Auth.sanpham = null;
        updateStatus();
        this.fillMenu();
    }
    
    
    //đổ csdl menu vào list menu bằng cách add panel
    public void fillMenu(){
        pnlKhaivi.removeAll();
        pnlSushi.removeAll();
        pnlTempura.removeAll();
        pnlDiemtam.removeAll();
        pnlTrangMieng.removeAll();
        try{
            List<SanPham> spl = spd.selectAll();
            for(SanPham sp : spl){
                MenuPanelChild mnpnl = new MenuPanelChild(sp);
                mnpnl.setSize(200, 190);
                if(sp.getMaloai()==1)
                    pnlKhaivi.add(mnpnl);
                else if(sp.getMaloai()==2)
                    pnlSushi.add(mnpnl);
                else if(sp.getMaloai()==3)
                    pnlDiemtam.add(mnpnl);
                else if(sp.getMaloai()==4)
                    pnlTempura.add(mnpnl);
                else
                    pnlTrangMieng.add(mnpnl);
            }
        }
        catch(Exception ex){
            //MsgBox.alert(this, "Lỗi kết nối dữ liệu");
            throw new RuntimeException(ex);
        }
    }
    
    //setForm
    public static void setForm(SanPham sp){
        txtTenmon.setText(sp.getTenSp());
        txtGia.setText(String.valueOf(sp.getDonGia()));     
        txtMota.setText(sp.getMota());
        
        if(sp.getMaloai()==1)                                                   //set loại
            cboLoai.setSelectedIndex(0);
        else if(sp.getMaloai()==2)
            cboLoai.setSelectedIndex(1);
        else if(sp.getMaloai()==3)
            cboLoai.setSelectedIndex(2);
        else if(sp.getMaloai()==4)
            cboLoai.setSelectedIndex(3);
        else
            cboLoai.setSelectedIndex(4);
        
        if(sp.getTinhTrang())                                                   //set tình trạng
            rdoCon.setSelected(true);
        else
            rdoHet.setSelected(true);
        
        loadImg(sp.getHinh());
        updateStatus();
    }    
    
    //getForm
    public SanPham getForm(){
        SanPham sp = new SanPham();
        sp.getHinh();
        sp.setTenSp(txtTenmon.getText());
        sp.setDonGia(Double.valueOf(txtGia.getText().toString()));
        
        if(cboLoai.getSelectedIndex()==0)
            sp.setMaloai(1);
        else if(cboLoai.getSelectedIndex()==1)
            sp.setMaloai(2);
        else if(cboLoai.getSelectedIndex()==2)
            sp.setMaloai(3);
        else if(cboLoai.getSelectedIndex()==3)
            sp.setMaloai(4);
        else
            sp.setMaloai(5);
        
        if(rdoCon.isSelected())
            sp.setTinhTrang(true);
        else 
            sp.setTinhTrang(false);
        
        sp.setMota(txtMota.getText());
        sp.setHinh(lblHinh.getToolTipText());
        return sp;
    }
    
    
    //clearForm
    public void clearForm(){        
        txtTenmon.setText("");
        txtGia.setText("00");
        rdoCon.setSelected(true);
        txtMota.setText("");
        cboLoai.setSelectedIndex(0);
        lblHinh.setIcon(null);
        lblHinh.setToolTipText(null);
        
        Auth.sanpham = null;
        updateStatus();
    }
    
    //load img
    public static void loadImg(String name){
        lblHinh.setSize(197, 138);
        ImageIcon avata = XImage.readImg(name, lblHinh);
        lblHinh.setIcon(avata);
        lblHinh.setToolTipText(name);
    }
    
    //chọn và đọc img
    public void getImg(){
        JFileChooser fChooser = new JFileChooser();
        if(fChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File file = fChooser.getSelectedFile();
            XImage.saveImg(file);                                               //lưu file
            loadImg(file.getName());
        }
    }
    
    
    //update status
    public static void updateStatus(){
        if(Auth.sanpham != null){
            resetBtn(btnMoi);
            resetBtn(btnSua);
            resetBtn(btnXoa);
            setBtn(btnThem);           
        }
        else{
            resetBtn(btnMoi);
            resetBtn(btnThem);
            setBtn(btnSua);
            setBtn(btnXoa);
        }
    }
    
    //set status cho btn
    public static void setBtn(KButton btn){
        btn.setEnabled(false);
        btn.setkStartColor(new Color(204,204,204));
    }
    
    //reset status cho btn
    public static void resetBtn(KButton btn){
        btn.setEnabled(true);
        btn.setkStartColor(new Color(153,255,153));
    }
    
    //check validate
    public boolean checkValidate(){
        try{
            Double gia = Double.valueOf(txtGia.getText().toString().trim());
            if(txtTenmon.getText().length()== 0){
                MsgBox.alert(this, "Vui lòng nhập tên sp");
                return false;
            }
            else if(txtGia.getText().length()==0 || gia < 20000){
                MsgBox.alert(this, "Vui lòng nhập giá món ăn > 20k ");
                return false;
            }
            else if(txtMota.getText().length()==0){
                MsgBox.alert(this, "Vui lòng nhập mô tả cho sản phẩm");
                return false;
            }
            else
                return true;
        }
        catch(Exception e){
            MsgBox.alert(this, "Giá món ăn phải thể hiện bằng số");
            return false;
        }
        
    }
    
    //check tên trùng ( mã tự tăng nên ko cần xét, còn về tên món ăn thì trên thực tế 1 tên món chỉ dùng 1 lần)
    public boolean checkName(){
        String name = txtTenmon.getText();
        SanPham sp = spd.selectByName(name);
        if(sp == null)
            return true;
        else{
            MsgBox.alert(this, "Tên món ăn này đã xuất hiện trong menu");
            return false;
        }           
    }
    
    //thêm mới
    public void addSP(){
        if(this.checkValidate()){
            if(this.checkName()){
                try{
                    SanPham sp = this.getForm();
                    spd.insert(sp);
                    fillMenu();
                    MsgBox.alert(this, "Thêm mới thành công");
                    this.clearForm();
                    updateStatus();
                }
                catch(Exception e){
                    MsgBox.alert(this, "Thêm thất bại");
                    throw new RuntimeException(e);
                }
            }
        }
    }
    
    //chỉnh sửa sản phẩm
    public void editSP(){
        if(this.checkValidate()){
            if(txtTenmon.getText().toString().equalsIgnoreCase(Auth.sanpham.getTenSp()) || this.checkName()){
                try{
                    SanPham sp = this.getForm();
                    sp.setMaSp(Auth.sanpham.getMaSp());
                    spd.update(sp);
                    Auth.sanpham = sp;
                    fillMenu();
                    MsgBox.alert(this, "Cập nhật thành công");
                    updateStatus();
                }
                catch(Exception e){
                    MsgBox.alert(this, "Edit thất bại");
                    throw new RuntimeException(e);
                }
            }
        }
    }
    
    //xóa sp
    public void deleteSP(){
        if(MsgBox.confirm(this, "Bạn muốn xóa Sản phẩm : "+Auth.sanpham.getTenSp())){
            try{
                spd.delete(String.valueOf(Auth.sanpham.getMaSp()));
                clearForm();
                fillMenu();
                MsgBox.alert(this, "Đã xóa");
                updateStatus();
            }
            catch(Exception e){
                MsgBox.alert(this, "Xóa thất bại");
                throw new RuntimeException(e);
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static keeptoo.KButton btnMoi;
    public static keeptoo.KButton btnSua;
    public static keeptoo.KButton btnThem;
    public static keeptoo.KButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel486;
    private javax.swing.JLabel jLabel487;
    private javax.swing.JLabel jLabel488;
    private javax.swing.JLabel jLabel489;
    private javax.swing.JLabel jLabel490;
    private javax.swing.JLabel jLabel491;
    private javax.swing.JLabel jLabel513;
    private javax.swing.JLabel jLabel514;
    private javax.swing.JLabel jLabel515;
    private javax.swing.JLabel jLabel516;
    private javax.swing.JLabel jLabel517;
    private javax.swing.JLabel jLabel518;
    private javax.swing.JLabel jLabel519;
    private javax.swing.JLabel jLabel520;
    private javax.swing.JLabel jLabel521;
    private javax.swing.JLabel jLabel522;
    private javax.swing.JLabel jLabel523;
    private javax.swing.JLabel jLabel524;
    private javax.swing.JLabel jLabel525;
    private javax.swing.JLabel jLabel526;
    private javax.swing.JLabel jLabel527;
    private javax.swing.JLabel jLabel528;
    private javax.swing.JLabel jLabel529;
    private javax.swing.JLabel jLabel530;
    private javax.swing.JLabel jLabel531;
    private javax.swing.JLabel jLabel532;
    private javax.swing.JLabel jLabel533;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel161;
    private javax.swing.JPanel jPanel162;
    private javax.swing.JPanel jPanel170;
    private javax.swing.JPanel jPanel171;
    private javax.swing.JPanel jPanel172;
    private javax.swing.JPanel jPanel173;
    private javax.swing.JPanel jPanel174;
    private javax.swing.JPanel jPanel175;
    private javax.swing.JPanel jPanel176;
    private javax.swing.JPanel jPanel51;
    public static javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JTabbedPane jTabbedPane4;
    public static javax.swing.JLabel lblHinh;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnlChitiet;
    private javax.swing.JPanel pnlDiemtam;
    private javax.swing.JPanel pnlKhaivi;
    private javax.swing.JPanel pnlSushi;
    private javax.swing.JPanel pnlTempura;
    private javax.swing.JPanel pnlTrangMieng;
    public static javax.swing.JRadioButton rdoCon;
    public static javax.swing.JRadioButton rdoHet;
    public static javax.swing.JTextField txtGia;
    public static javax.swing.JTextArea txtMota;
    public static javax.swing.JTextField txtTenmon;
    // End of variables declaration//GEN-END:variables
}
